session:
    name: "dev"
    windows: 
        - name: "pipeline"
          root: '~/projects/pipeline'
          panes:
            - cmd: "vim ."
              focus: true
            - cmd: "tail -f log/*"
              width: 40
            - cmd: "bundle exec tdd --growl rake"
              height: 66 
            - cmd: "t ls"
              height: 50 
